cache.filter.include.user.agent=false
com.liferay.portal.servlet.filters.cache.CacheFilter=false
passwords.default.policy.change.required=false
session.timeout=120
setup.wizard.enabled=false
terms.of.use.required=false
users.reminder.queries.enabled=false
default.admin.password=test
enterprise.product.notification.enabled=false
company.login.prepopulate.domain=false
company.security.strangers.with.mx=false
company.security.auto.login=false
company.security.strangers=false
company.security.strangers.verify=false
company.security.send.password.reset.link=false
company.security.update.password.required=false
layout.user.private.layouts.enabled=false
layout.user.private.layouts.auto.create=false
layout.user.public.layouts.enabled=false
layout.user.public.layouts.auto.create=false
field.enable.com.liferay.portal.kernel.model.Contact.male=false
field.enable.com.liferay.portal.kernel.model.Contact.birthday=false
session.timeout.auto.extend=true
session.timeout.auto.extend.offset=10
feature.flag.ui.visible[dev]=true
dl.file.entry.preview.image.mime.types=image/bmp,\
image/gif,\
image/jpeg,\
image/pjpeg,\
image/png,\
image/tiff,\
image/x-citrix-jpeg,\
image/x-citrix-png,\
image/x-ms-bmp,\
image/x-png,\
image/x-tiff,\
image/webp,\
image/avif
feature.flag.LPD-35443=true
feature.flag.LPS-178052=true
captcha.enforce.disabled=true
captcha.check.portal.create_account=false
captcha.check.portal.send_password=false
live.users.enabled=true
passwords.passwordpolicytoolkit.generator=static
passwords.passwordpolicytoolkit.static=test
users.last.name.required=false
users.reminder.queries.custom.question.enabled=false
module.framework.properties.com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.operationMode=EMBEDDED
module.framework.properties.com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.sidecarHttpPort=9201
module.framework.properties.com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.sidecarTransportTcpPort=9301
module.framework.properties.com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.transportTcpPort=9301
module.framework.properties.com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.sidecarNetworkHost=0.0.0.0
module.framework.properties.com.liferay.portal.search.elasticsearch8.configuration.ElasticsearchConfiguration.operationMode=EMBEDDED
module.framework.properties.com.liferay.portal.search.elasticsearch8.configuration.ElasticsearchConfiguration.sidecarHttpPort=9201
module.framework.properties.com.liferay.portal.search.elasticsearch8.configuration.ElasticsearchConfiguration.sidecarTransportTcpPort=9301
module.framework.properties.com.liferay.portal.search.elasticsearch8.configuration.ElasticsearchConfiguration.transportTcpPort=9301
module.framework.properties.com.liferay.portal.search.elasticsearch8.configuration.ElasticsearchConfiguration.sidecarNetworkHost=0.0.0.0
jdbc.default.driverClassName=org.postgresql.Driver
jdbc.default.url=jdbc:postgresql://db:5432/lportal
jdbc.default.username=lportal
jdbc.default.password=test
hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
