services:
  liferay:
    image: "liferay/dxp:2026.q1.7-lts"
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - "LIFERAY_JVM_OPTS=-Xms2048m -Xmx3072m -XX:MaxMetaspaceSize=512m -XX:MetaspaceSize=512m -XX:NewSize=1013m -XX:MaxNewSize=1013m -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF8 -Duser.timezone=GMT --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/sun.net.www.protocol.http=ALL-UNNAMED --add-opens=java.base/sun.net.www.protocol.https=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED --add-opens=java.base/sun.security.util=ALL-UNNAMED --add-opens=java.base/sun.security.x509=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED --add-opens=jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -Djdk.util.zip.disableZip64ExtraFieldValidation=true"
      - "LIFERAY_LOG4J2_CONFIGURATION_FILE=/opt/liferay/osgi/log4j/portal-log4j-ext.xml"
      - "LIFERAY_ELASTICSEARCH_PERIOD_PRODUCTION_PERIOD_MODE_PERIOD_ENABLED=false"
      - "LIFERAY_ELASTICSEARCH_PERIOD_SIDECAR_PERIOD_ENABLED=true"
      - "LIFERAY_ELASTICSEARCH_PERIOD_OPERATION_PERIOD_MODE=EMBEDDED"
      - "LIFERAY_HSQL_PERIOD_ENABLED=false"
    labels:
      - "com.liferay.ldm.project=liferay-ai-commerce-accelerator"
      - "com.liferay.ldm.managed=true"
    volumes:
      - "/Volumes/SanDisk/repos/liferay-fragments/liferay-ai-commerce-accelerator/deploy:/mnt/liferay/deploy"
      - "/Volumes/SanDisk/repos/liferay-fragments/liferay-ai-commerce-accelerator/files:/mnt/liferay/files"
      - "/Volumes/SanDisk/repos/liferay-fragments/liferay-ai-commerce-accelerator/scripts:/mnt/liferay/scripts"
      - "liferay-ai-commerce-accelerator-data:/opt/liferay/data"
      - "/Volumes/SanDisk/repos/liferay-fragments/liferay-ai-commerce-accelerator/osgi/modules:/opt/liferay/osgi/modules"
      - "/Volumes/SanDisk/repos/liferay-fragments/liferay-ai-commerce-accelerator/osgi/client-extensions:/opt/liferay/osgi/client-extensions"
      - "/Volumes/SanDisk/repos/liferay-fragments/liferay-ai-commerce-accelerator/osgi/portal-log4j:/opt/liferay/osgi/log4j"
      - "liferay-ai-commerce-accelerator-state:/opt/liferay/osgi/state"
      - "/Volumes/SanDisk/repos/liferay-fragments/liferay-ai-commerce-accelerator/logs:/opt/liferay/logs"
    networks:
      - "liferay-net"
    depends_on:
      db:
        condition: "service_healthy"
    container_name: "liferay-ai-commerce-accelerator"
  db:
    image: "postgres:16.2"
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=1024MB"
      - "-c"
      - "max_connections=200"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "lportal"
      POSTGRES_DB: "lportal"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U lportal"
      interval: "10s"
      timeout: "5s"
      retries: 10
      start_period: "60s"
    networks:
      - "liferay-net"
    container_name: "liferay-ai-commerce-accelerator-db"
    labels:
      - "com.liferay.ldm.project=liferay-ai-commerce-accelerator"
      - "com.liferay.ldm.managed=true"
  lfr-tunnel:
    image: "peterjrichards/lfr-tunnel:latest"
    pull_policy: "always"
    container_name: "liferay-ai-commerce-accelerator-lfr-tunnel"
    networks:
      - "liferay-net"
    environment:
      - "LFT_CLIENT_TOKEN=${LFT_CLIENT_TOKEN:-0484eee3bca6c3d44eb74b98a7814202}"
      - "LFT_TARGET_HOST=liferay"
      - "LFT_CLIENT_SUBDOMAIN=${LFT_SUBDOMAIN:-pjrtest}"
      - "LFT_PRESERVE_HOST=true"
      - "LFT_INSPECTOR_BIND=${LFT_INSPECTOR_BIND:-0.0.0.0}"
      - "LFT_CLIENT_SERVER=${LFT_SERVER_URL:-https://tunnel.lfr-demo.online}"
    volumes:
      - "/Volumes/SanDisk/repos/liferay-fragments/liferay-ai-commerce-accelerator/logs:/opt/liferay/logs"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "./lfr-tunnel 2>&1 | tee /opt/liferay/logs/lfr-tunnel.log"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50M"
        reservations:
          cpus: "0.05"
          memory: "20M"
    depends_on:
      liferay:
        condition: "service_healthy"
    labels:
      - "com.liferay.ldm.project=liferay-ai-commerce-accelerator"
      - "com.liferay.ldm.managed=true"
networks:
  liferay-net:
    external: true
volumes:
  liferay-ai-commerce-accelerator-data:
    name: "liferay-ai-commerce-accelerator-data"
  liferay-ai-commerce-accelerator-state:
    name: "liferay-ai-commerce-accelerator-state"