services:
  liferay:
    image: "liferay/dxp:2026.q1.9-lts"
    ports:
      - "127.0.0.1:8090:8080"
    environment:
      - "LIFERAY_JVM_OPTS=-Xms2048m -Xmx4096m -XX:MaxMetaspaceSize=768m -XX:MetaspaceSize=768m -XX:NewSize=1536m -XX:MaxNewSize=1536m -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF8 -Duser.timezone=GMT --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/sun.net.www.protocol.http=ALL-UNNAMED --add-opens=java.base/sun.net.www.protocol.https=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.security.ssl=ALL-UNNAMED --add-opens=java.base/sun.security.util=ALL-UNNAMED --add-opens=java.base/sun.security.x509=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED --add-opens=jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED -Djdk.util.zip.disableZip64ExtraFieldValidation=true"
      - "LIFERAY_LOG4J2_CONFIGURATION_FILE=/opt/liferay/osgi/log4j/portal-log4j-ext.xml"
      - "LIFERAY_ELASTICSEARCH_PERIOD_PRODUCTION_PERIOD_MODE_PERIOD_ENABLED=false"
      - "LIFERAY_ELASTICSEARCH_PERIOD_SIDECAR_PERIOD_ENABLED=true"
      - "LIFERAY_ELASTICSEARCH_PERIOD_OPERATION_PERIOD_MODE=EMBEDDED"
      - "LIFERAY_HSQL_PERIOD_ENABLED=false"
    labels:
      - "com.liferay.ldm.project=e2e-test-env"
      - "com.liferay.ldm.managed=true"
    volumes:
      - "D:/repos/liferay-fragments/e2e-test-env/deploy:/mnt/liferay/deploy"
      - "D:/repos/liferay-fragments/e2e-test-env/files:/mnt/liferay/files"
      - "D:/repos/liferay-fragments/e2e-test-env/scripts:/mnt/liferay/scripts"
      - "e2e-test-env-data:/opt/liferay/data"
      - "D:/repos/liferay-fragments/e2e-test-env/osgi/modules:/opt/liferay/osgi/modules"
      - "D:/repos/liferay-fragments/e2e-test-env/osgi/client-extensions:/opt/liferay/osgi/client-extensions"
      - "D:/repos/liferay-fragments/e2e-test-env/osgi/portal-log4j:/opt/liferay/osgi/log4j"
      - "e2e-test-env-state:/opt/liferay/osgi/state"
      - "D:/repos/liferay-fragments/e2e-test-env/logs:/opt/liferay/logs"
    networks:
      - "liferay-net"
    depends_on:
      db:
        condition: "service_healthy"
    container_name: "e2e-test-env"
  db:
    image: "postgres:16.2"
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=1024MB"
      - "-c"
      - "max_connections=200"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "lportal"
      POSTGRES_DB: "lportal"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U lportal"
      interval: "10s"
      timeout: "5s"
      retries: 10
      start_period: "60s"
    networks:
      - "liferay-net"
    container_name: "e2e-test-env-db"
    labels:
      - "com.liferay.ldm.project=e2e-test-env"
      - "com.liferay.ldm.managed=true"
networks:
  liferay-net:
    external: true
volumes:
  D:
    name: "D"
  e2e-test-env-data:
    name: "e2e-test-env-data"
  e2e-test-env-state:
    name: "e2e-test-env-state"