cache.filter.include.user.agent=false
enterprise.product.notification.enabled=false
users.reminder.queries.enabled=false
layout.user.private.layouts.enabled=false
setup.wizard.enabled=false
company.security.update.password.required=false
field.enable.com.liferay.portal.kernel.model.Contact.male=false
company.security.strangers=false
company.login.prepopulate.domain=false
company.security.strangers.with.mx=false
include-and-override=portal-developer.properties
default.admin.password=test
company.security.strangers.verify=false
layout.user.public.layouts.enabled=false
passwords.default.policy.change.required=false
company.security.send.password.reset.link=false
dl.file.entry.preview.image.mime.types=image/bmp,\
image/gif,\
image/jpeg,\
image/pjpeg,\
image/png,\
image/tiff,\
image/x-citrix-jpeg,\
image/x-citrix-png,\
image/x-ms-bmp,\
image/x-png,\
image/x-tiff,\
image/webp,\
image/avif
session.timeout=120
feature.flag.LPD-35443=true
terms.of.use.required=false
com.liferay.portal.servlet.filters.cache.CacheFilter=false
feature.flag.ui.visible[dev]=true
feature.flag.LPS-178052=true
company.security.auto.login=false
layout.user.private.layouts.auto.create=false
layout.user.public.layouts.auto.create=false
session.timeout.auto.extend.offset=10
session.timeout.auto.extend=true
field.enable.com.liferay.portal.kernel.model.Contact.birthday=false
captcha.enforce.disabled=false
